
# Travis CI build and test file for ActivityLog2.  The aim is to check that
# the application builds correctly, and automated tests pass.  The build step
# runs build.rkt which also creates a distribution (in the past, creating a
# distribution has failed due to bad paths in `define-runtime-path`).  Some of
# the automated tests depend on data that is downloaded from Google Drive,
# this is private data and it is encrypted.  It is downloaded by the
# `download-test-data.sh` script.

# Some notes:

# The "secure" part will not be decrypted on pull requests that are from
# outside the main repository (this actually makes sense, if you think about
# it) -- tests that depend on private data will only run on the official
# branches.

# Do not use caching of any kind, it is not really needed and possibly not a
# good idea when combined with the `download-test-data.sh`

# The Racket tests require an X server, since they link into the GUI
# libraries, even though they don't open any GUI windows, thus we have a
# DISPLAY environment variable and we start `xvfb`

# References:

# https://docs.travis-ci.com/user/caching/
# https://docs.travis-ci.com/user/encryption-keys/

language: c
sudo: false
cache: false

env:
  global:
    - RACKET_DIR=~/racket
    - DISPLAY=:99.0
    - secure: "UrtMaEd9RcXMSEaOK/0VJh7W5L1MIAIjcZnh38pHt/xDIRDCXhMNxkMCS6ra00UwrFaw1l3VcI5mNYWY1JP6Fct1LbU2AY+sKoNNkld5OigNUrx1eXhtzXy8a1T0gX0kJhWvPVAActRwnaWjmhUblH1UAOWOvfcX4laekAVXbSJOVCBKSQl7HNl0xJBm0TriAZtWg+pumTG93e2+3hza6cWQ0tJHqn1kwBmD6aKTJLpd05IU3g6bl/+4cOGosnOaD8L/fDjA51Hl5kwHXPxTrNkoLqRdrCfX+q5vF9D6qG6VdS4lxiNKDTCvnKQ8TZXsvF+WIvIaQSR8CrqqO5pfZWHQNkMJ6jIFrLrV77xx5fa4wWamOgeoZ2GhkXjlg/0qVTVU30h4qZbijbP7byyyErLKujklIYJPgRcgp8ok7pMs4qyqMK7lWyrwYQ7lc/e0PvS/stz8tGSVMboHsVFcP1IlQHAaQJK7Nlk3Pzxktx9CtOHOn/DW7Bw+eRd/zF24GqZKBwxB5VbgBWxpPfukWUwejo/uIevMGGSDnPOmNXvWeQL0LJ8C6qKUSfaH9+5YGwkev46MH41KyWfyekqjbASxNx3MU7SXeFrwT/5jQVENhD/zAUVMVk4Nr6YmAWm1iD66RvpJ/Y3lHn0roQ3CUVKWsHR/l5cNd8SYx5RT7nU="
  matrix:
    - RACKET_VERSION=7.0
matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=RELEASE
  fast_finish: true
before_install:
  - bash ./.travis/install-racket.sh
  - export PATH="${RACKET_DIR}/bin:${PATH}"
install: true
before_script:
  - bash -e /etc/init.d/xvfb start
  - bash ./.travis/download-test-data.sh
script:
  - racket build.rkt
  - raco test test/df-test.rkt
  - raco test test/db-test.rkt
  - raco test test/db-upgrade-test.rkt
  - raco test test/aggregate-test.rkt
  - raco test test/fit-test.rkt
after_script: 
